package com.example.testdeploysecondapp;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class TestDeploySecondAppApplicationTests {

    @Test
    void contextLoads() {
        // Autogenerated sample test
    }

}
